version: "2"
services:
  mongo:
    image: mongo:4.1.6
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "RiaDAMKG1SyU"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"