swagger: '2.0'
info:
  description: >-
    Appointments API
  version: 0.0.1
  title: Appointments API
basePath: /appointments/api
tags:
  - name: appointments
    description: appointments
  - name: patients
    description: patients
  - name: doctors
    description: doctors
schemes:
  - http
paths:
  /patients:
    post:
      tags:
        - patients
      summary: Create a patient
      description: Create a patient
      operationId: postPatient
      produces:
          - application/json
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Patient"
        400:
          description: bad request
  /doctors:
    post:
      tags:
        - doctors
      summary: Create a doctor
      description: Create a doctor
      operationId: postDoctor
      produces:
          - application/json
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Doctor"
        400:
          description: bad request
  /doctors/{id}: 
    get:
      tags:
        - doctors
      summary: Find a doctor's working hours
      description: Find a doctor's working hours
      operationId: getDoctorsById
      produces:
          - application/json
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Doctor"
        404:
          description: not found
  /doctors/{id}/working-days:
    patch:
      tags:
        - doctors
      summary: Updates a doctor's working hours
      description: Updates a doctor's working hours
      operationId: patchWorkingHoursByDoctorId
      parameters:
      - in: "body"
        name: "body"
        description: "Updates a doctor's working hours"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/Appointment"
      produces:
          - application/json
      responses:
        '200':
          description: successful operation
        '206':
          description: no content
  /appointments:  
    post:
      tags:
        - appointments
      summary: Book an doctor opening
      description: Book an doctor opening
      operationId: postAppointments
      parameters:
      - in: "body"
        name: "body"
        description: "Appointment object that needs to be booked"
        required: true
        schema:
          $ref: "#/definitions/Appointment"
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
        '422':
          description: Invalid status value 
definitions:
  Doctor:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
      workingDays:
        type: "array"
        items:
          $ref: "#/definitions/WorkingDay"
  TimeRange:
    type: "object"
    properties:
      start:
        type: "string"
      end:
        type: "string"
  WorkingDay:
    type: "object"
    properties:
      weekDay:
        type: "string"
        enum:
          - "Monday"
          - "Tuesday"
          - "Wednesday"
          - "Thursday"
          - "Friday"
          - "Saturday"
          - "Sunday"
      times:
        type: "array"
        items:
          $ref: "#/definitions/TimeRange"
  Appointment:
    type: "object"
    properties:
      id:
        type: "string"  
      doctorId:
        type: "string" 
      patientId:
        type: "string"        
      due:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Appointment Status"
        enum:
        - "scheduled"
        - "canceled"
        - "completed"
  Patient:
    type: "object"
    properties:
      id:
        type: "string"      
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"      
